### ISSUE TITLE
when i run katana ,there have an error is about dbus

### ISSUE THREAD

**Issue by littleheary** [JohnHammond/katana#1]
i have run it in ubuntu 16.04,python 3.7
i have install python-dbus
but still have error

Traceback (most recent call last):
  File "/ctf/katana/env/bin/katana", line 11, in <module>
    load_entry_point('katana==2.0', 'console_scripts', 'katana')()
  File "/ctf/katana/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/ctf/katana/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/ctf/katana/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/ctf/katana/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/ctf/katana/env/lib/python3.7/site-packages/katana-2.0-py3.7.egg/katana/__main__.py", line 10, in <module>
    from katana.repl import Repl, ReplMonitor
  File "/ctf/katana/env/lib/python3.7/site-packages/katana-2.0-py3.7.egg/katana/repl/__init__.py", line 12, in <module>
    import notify2
  File "/ctf/katana/env/lib/python3.7/site-packages/notify2-0.3.1-py3.7.egg/notify2.py", line 39, in <module>
    import dbus
  File "/usr/lib/python3/dist-packages/dbus/__init__.py", line 82, in <module>
    import dbus.types as types
  File "/usr/lib/python3/dist-packages/dbus/types.py", line 6, in <module>
    from _dbus_bindings import (
ModuleNotFoundError: No module named '_dbus_bindings'

**Comment by JohnHammond** [comment]
Had you created installed `python3-dev python3-dbus` before creating the virtual environment, and created the virtual environment with `--system-site-packages`?

```
sudo apt install -y python3-dev python3-dbus
python3.7 -m venv --system-site-packages env
```

**Comment by littleheary** [comment]
yes，i have install all of this
and the install step is use your readme.md to do everything

**Comment by JohnHammond** [comment]
This looks like an issue because Ubuntu 16.04 ships with Python 3.5, and Katana runs off of Python3.7 or later. I set up an Ubuntu 16.04 VM and attempting to troubleshoot this -- have you installed Python3.7 on that machine?

**Comment by littleheary** [comment]
yes,i have remove python 3.5 ,and install python 3.7.6
you can see my traceback infor,it is in python 3.7
this error i can't solve it ,so now i have use docker,it is work success.

**Comment by calebstewart** [comment]
Don't use `--system-site-packages`. If you have `python3.7` installed, you should just need to install the requirements in your virtual environment, and it will work. I just tested with a 16.04 image. I used `ppa:deadsnakes/ppa` to get python3.7, and then proceeded like normal with the base packages (admittedly, taken from the Dockerfile, not the README.md). I then setup a virtual environment with:

```
virtualenv ./env
. env/bin/activate
cd katana
pip install -r requirements
```
Then, starting katana with `python -m katana` worked as expected.

**Comment by calebstewart** [comment]
I updated the README to reflect those changes. `system-site-packages` defeats a lot of the purpose of virtual environments (e.g. having a clean environment) to begin with. It also causes problems when your OS is very out of date and the system packages aren't even compatible. That is likely the issue.

**Comment by JohnHammond** [comment]
@littleheary when you can, please give this ago and let us know if it resolves the problem. Following that we can close the issue.

**Comment by l3ouu4n9** [comment]
> Don't use `--system-site-packages`. If you have `python3.7` installed, you should just need to install the requirements in your virtual environment, and it will work. I just tested with a 16.04 image. I used `ppa:deadsnakes/ppa` to get python3.7, and then proceeded like normal with the base packages (admittedly, taken from the Dockerfile, not the README.md). I then setup a virtual environment with:
> 
> ```
> virtualenv ./env
> . env/bin/activate
> cd katana
> pip install -r requirements
> ```
> 
> Then, starting katana with `python -m katana` worked as expected.

I got the same issue with Ubuntu 18.04, and these instructions work perfectly to solve the problem and run katana successfully. Thanks for helping !

**Comment by JohnHammond** [comment]
@littleheary , had you had any success? Good to hear @l3ouu4n9 got it resolved!

**Comment by littleheary** [comment]
sorry,i have many days not login,i have use docker to run katana after this ,and docker run is success, so now i use docker to work.

**Comment by Wassim58** [comment]
katana --force -f "FLAG{.*?}" "RkxBR3t0aGlzX2lzX2FfYmFzZTY0X2ZsYWd9"
Traceback (most recent call last):
  File "/opt/katana/env/bin/katana", line 11, in <module>
    load_entry_point('katana==2.0', 'console_scripts', 'katana')()
  File "/opt/katana/env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/katana/env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/opt/katana/env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/opt/katana/env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/katana/env/lib/python3.9/site-packages/katana-2.0-py3.9.egg/katana/__main__.py", line 10, in <module>
    from katana.repl import Repl, ReplMonitor
  File "/opt/katana/env/lib/python3.9/site-packages/katana-2.0-py3.9.egg/katana/repl/__init__.py", line 301, in <module>
    class Repl(cmd2.Cmd):
  File "/opt/katana/env/lib/python3.9/site-packages/katana-2.0-py3.9.egg/katana/repl/__init__.py", line 587, in Repl
    monitor_remove_parser.add_argument(
  File "/opt/katana/env/lib/python3.9/site-packages/cmd2-2.3.3-py3.9.egg/cmd2/argparse_custom.py", line 866, in _add_argument_wrapper
    new_arg = orig_actions_container_add_argument(self, *args, **kwargs)
  File "/usr/lib/python3.9/argparse.py", line 1431, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'choices_method'
