### ISSUE TITLE
Error use (how can i do plz?) thks

### ISSUE THREAD

**Issue by tw1nsdrag0ns** [JohnHammond/katana#26]
Traceback (most recent call last):
  File "/home/ubuntu/Katana/bin/katana", line 11, in <module>
    load_entry_point('katana', 'console_scripts', 'katana')()
  File "/home/ubuntu/Katana/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/Katana/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/ubuntu/Katana/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/ubuntu/Katana/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ubuntu/Katana/katana.py", line 4, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

**Comment by calebstewart** [comment]
Hi, in the future, please wrap any output in three backticks like this:

````
```
Your output goes here
```
````

Next, please include a description of your problem. What were you trying to do? What command did you run? What kind of computer/operating system are you running on? How did you install katana? There's no way for us to guess these types of things. Every computer is different, and the problem could simply be a special case due to your specific environment. These are all things that will help the debugging process.

Regarding the traceback you posted, can you tell me how you installed `katana`? Obviously, there are depenencies missing which shouldn't happen if it was installed according to the [documentation](https://ctf-katana.readthedocs.io/en/latest/installation.html#installation-instructions).
