### ISSUE TITLE
can't access docker ...

### ISSUE THREAD

**Issue by mayomacam** [JohnHammond/katana#30]
I create docker image of katana but i can't access it...
```
(base) ┌─[root@parrot]─[/home/mayomacam/Videos/tool/katana]
└──╼ #docker images
REPOSITORY   TAG       IMAGE ID       CREATED             SIZE
katana       latest    9cc4dabcf59c   About an hour ago   2.29GB
python       3.8       b0358f6298cd   3 days ago          882MB
(base) ┌─[root@parrot]─[/home/mayomacam/Videos/tool/katana]
└──╼ #docker run -it katana
[+] checking for updates
[+] katana is up to date!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/katana/katana/__main__.py", line 175, in <module>
    main()
  File "/katana/katana/__main__.py", line 36, in main
    manager = Manager(monitor=monitor, config_path=args.config)
  File "/katana/katana/manager.py", line 99, in __init__
    raise RuntimeError("{0}: configuration file not found")
RuntimeError: {0}: configuration file not found
```
i edit the docker run command above
```
(base) ┌─[✗]─[root@parrot]─[/home/mayomacam/Videos/tool/katana]
└──╼ #docker run -v "$(CTF_DIRECTORY):data" -it katana
CTF_DIRECTORY: command not found
[+] checking for updates
[+] katana is up to date!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/katana/katana/__main__.py", line 175, in <module>
    main()
  File "/katana/katana/__main__.py", line 36, in main
    manager = Manager(monitor=monitor, config_path=args.config)
  File "/katana/katana/manager.py", line 99, in __init__
    raise RuntimeError("{0}: configuration file not found")
RuntimeError: {0}: configuration file not found
```

**Comment by Aegizz** [comment]
Hey did you solve this I have the same issue?

**Comment by mayomacam** [comment]
No I just didn't choose docker as I had install for some other reason
