### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'choices_method'

### ISSUE THREAD

**Issue by NoXLaw** [JohnHammond/katana#33]
➜  katana git:(master) katana
Traceback (most recent call last):
  File "/usr/local/bin/katana", line 11, in <module>
    load_entry_point('katana==2.0', 'console_scripts', 'katana')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/katana-2.0-py3.8.egg/katana/__main__.py", line 10, in <module>
    from katana.repl import Repl, ReplMonitor
  File "/usr/local/lib/python3.8/dist-packages/katana-2.0-py3.8.egg/katana/repl/__init__.py", line 301, in <module>
    class Repl(cmd2.Cmd):
  File "/usr/local/lib/python3.8/dist-packages/katana-2.0-py3.8.egg/katana/repl/__init__.py", line 587, in Repl
    monitor_remove_parser.add_argument(
  File "/usr/local/lib/python3.8/dist-packages/cmd2-2.1.1-py3.8.egg/cmd2/argparse_custom.py", line 562, in _add_argument_wrapper
    new_arg = orig_actions_container_add_argument(self, *args, **kwargs)
  File "/usr/lib/python3.8/argparse.py", line 1380, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'choices_method'

**Comment by sbower** [comment]
I'm getting the same issue

**Comment by jeffg2k** [comment]
Me too, I don't think `choices_method` is a valid `add_argument`.  I think it should probably be `choices`.
https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_argument

**Comment by jeffg2k** [comment]
I even get this `choices_method` error in Docker.  I'll also note that to get docker to install, I had to replace `libenchant-dev` with `libenchant-2-dev` as libenchant-dev could not be found.

<img width="1236" alt="Screen Shot 2021-08-23 at 8 12 12 PM" src="https://user-images.githubusercontent.com/161904/130535339-d7147ead-fdc3-4225-9c02-b7fb45d29638.png">

**Comment by LocalsGitHub** [comment]
I am experiencing the same issue.

**Comment by levelnoah** [comment]
I am experiencing the same issue.

**Comment by hax3xploit** [comment]
```
1. pip uninstall cmd2
2. pip install cmd2=='1.0.1'
```
This will FIX your problem.

**Comment by levelnoah** [comment]
Thank you very much for the reply
It's working.
Later i will post this solution to your github Issues because some other people are having this problem



发自我的iPhone


------------------ Original ------------------
From: Abdullah Khawaja ***@***.***&gt;
Date: Tue,Sep 14,2021 1:20 PM
To: JohnHammond/katana ***@***.***&gt;
Cc: levelnoah ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [JohnHammond/katana] TypeError: __init__() got an unexpected keyword argument 'choices_method' (#33)





 1. pip uninstall cmd2 2. pip install cmd2=='1.0.1'  
This will FIX your problem.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jeffg2k** [comment]
Excellent - thanks for identifying the issue.  Since we now know the cause, I created a pull request that doesn't require a cmd2 downgrade.
https://github.com/JohnHammond/katana/pull/39

Note: If the PR is accepted, existing users that update Katana may need to update cmd2 or they'll get a similar error, `TypeError: __init__() got an unexpected keyword argument 'choices_provider'`.  `pip install cmd2 --upgrade`
