### ISSUE TITLE
docker installation failed: Unable to locate package libenchant-dev

### ISSUE THREAD

**Issue by dumprop** [JohnHammond/katana#42]
```
$ docker build -t katana .
Sending build context to Docker daemon  8.192kB
Step 1/25 : FROM python:3.8
3.8: Pulling from library/python
647acf3d48c2: Pull complete 
b02967ef0034: Pull complete 
e1ad2231829e: Pull complete 
5576ce26bf1d: Pull complete 
a66b7f31b095: Pull complete 
05189b5b2762: Pull complete 
3b0f50bca553: Pull complete 
75eb55df9bc7: Pull complete 
1f2ae3b45e17: Pull complete 
Digest: sha256:68bddbf6e88c9c88d3238e13f02edf1884fc349a0964fad4b3d44f2425791ac7
Status: Downloaded newer image for python:3.8
 ---> 67ec76d9f73b
Step 2/25 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Running in 447af247bfd4
Removing intermediate container 447af247bfd4
 ---> 80b2dc2c337f
Step 3/25 : RUN apt-get update -qq      && apt-get install -y -qq python-tk tk-dev libffi-dev libssl-dev pandoc     libgmp3-dev libzbar-dev tesseract-ocr xsel libpoppler-cpp-dev libmpc-dev         libdbus-glib-1-dev ruby libenchant-dev apktool nodejs groff binwalk  foremost tcpflow poppler-utils exiftool steghide stegsnow bison ffmpeg  libgd-dev less       && apt-get clean        && rm -rf /var/lib/apt/lists/*
 ---> Running in 15dd76dee6fa
E: Unable to locate package libenchant-dev
The command '/bin/sh -c apt-get update -qq      && apt-get install -y -qq python-tk tk-dev libffi-dev libssl-dev pandoc      libgmp3-dev libzbar-dev tesseract-ocr xsel libpoppler-cpp-dev libmpc-dev        libdbus-glib-1-dev ruby libenchant-dev apktool nodejs groff binwalk  foremost tcpflow poppler-utils exiftool steghide stegsnow bison ffmpeg  libgd-dev less       && apt-get clean        && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

```

**Comment by ptrcnull** [comment]
Changing base image to `python:3.8-buster` fixes that, but it's still broken in many ways - `colorama` is missing there are some errors with argparse:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/katana/katana/__main__.py", line 10, in <module>
    from katana.repl import Repl, ReplMonitor
  File "/katana/katana/repl/__init__.py", line 301, in <module>
    class Repl(cmd2.Cmd):
  File "/katana/katana/repl/__init__.py", line 587, in Repl
    monitor_remove_parser.add_argument(
  File "/usr/local/lib/python3.8/site-packages/cmd2/argparse_custom.py", line 866, in _add_argument_wrapper
    new_arg = orig_actions_container_add_argument(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/argparse.py", line 1368, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'choices_method'
```

**Comment by Jandrov** [comment]
I tried it some days ago and I fixed it by using `libenchant-2-dev` package, as the other one is not supported anymore (found it [here](https://stackoverflow.com/questions/68997416/docker-compose-built-doesnt-run-on-wagtail))
I am preparing a PR updating that.
