### ISSUE TITLE
No module named 'colorama' when try to run docker

### ISSUE THREAD

**Issue by matt-t-zz** [JohnHammond/katana#46]
As John mentioned in his video katana is 'infrequently maintained' and if I'm reading correctly the most recent update was 2 years ago. However, I hoped that someone may still be able to assist. EVen if only some of the functionality works I'd be interested to see it in action. I installed Linux for the first time this week and installed docker for the first time today so I may well be doing something simple wrong!

I used 'git clone [address]' to clone the project, I ran from my home directory. I went into katana/docker and ran 'docker build -t katana .'

I then ran the below in my home directory and I have a subdirectory called data, currently empty.

└─$ docker run -v $(pwd)/data:/data -it katana
[+] checking for updates
[+] katana is up to date!
**Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/katana/katana/__main__.py", line 10, in <module>
    from katana.repl import Repl, ReplMonitor
  File "/katana/katana/repl/__init__.py", line 20, in <module>
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'**

I searched around and believe I know how I would fix this error (pip install colorama) if this was coming up outside docker. However, I wasn't sure how to diagnose a message "within" docker

**Comment by Luke-lujunxian** [comment]
you may add `RUN pip install colorama` to the docker file and build it again
