### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'choices_method'

### ISSUE THREAD

**Issue by petport** [JohnHammond/katana#65]
Hey guys, got this error. Any insight?

(env) petros@DESKTOP-6MF9LET:~/katana$ katana
Traceback (most recent call last):
  File "/home/petros/katana/env/bin/katana", line 33, in <module>
    sys.exit(load_entry_point('katana==2.0', 'console_scripts', 'katana')())
  File "/home/petros/katana/env/bin/katana", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/petros/katana/env/lib/python3.7/site-packages/importlib_metadata-4.12.0-py3.7.egg/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/petros/katana/env/lib/python3.7/site-packages/katana-2.0-py3.7.egg/katana/__main__.py", line 10, in <module>
    from katana.repl import Repl, ReplMonitor
  File "/home/petros/katana/env/lib/python3.7/site-packages/katana-2.0-py3.7.egg/katana/repl/__init__.py", line 301, in <module>
    class Repl(cmd2.Cmd):
  File "/home/petros/katana/env/lib/python3.7/site-packages/katana-2.0-py3.7.egg/katana/repl/__init__.py", line 591, in Repl
    choices_method=get_monitor_choices,
  File "/home/petros/katana/env/lib/python3.7/site-packages/cmd2-2.4.1-py3.7.egg/cmd2/argparse_custom.py", line 866, in _add_argument_wrapper
    new_arg = orig_actions_container_add_argument(self, *args, **kwargs)
  File "/usr/lib/python3.7/argparse.py", line 1368, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'choices_method'

**Comment by petport** [comment]
1. pip uninstall cmd2
2. pip install cmd2=='1.0.1'
This will FIX your problem.

https://github.com/JohnHammond/katana/issues/33#issuecomment-918812803
